<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>VenEl.MCP.AWS</PackageId>
    <Version>1.0.1</Version>
    <Authors>VenEl</Authors>
    <Description>VenEl Core Business Logic - VenEl.MCP.AWS</Description>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.EC2" Version="4.0.89" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.23.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VenEl.MCP.Core\VenEl.MCP.Core.csproj" />
  </ItemGroup>

</Project>
