<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>VenEl.MCP.FTP</PackageId>
    <Version>1.0.1</Version>
    <Authors>VenEl</Authors>
    <Description>VenEl Core Business Logic - VenEl.MCP.FTP</Description>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="54.2.0" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VenEl.MCP.Core\VenEl.MCP.Core.csproj" />
  </ItemGroup>

</Project>
