<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VenEl.MCP.Core\VenEl.MCP.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" Version="1.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>VenEl.MCP.Host</PackageId>
    <Version>1.0.1</Version>
    <Authors>VenEl</Authors>
    <Description>VenEl Core Business Logic - VenEl.MCP.Host</Description>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
