<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>VenEl.MCP.MSSql</PackageId>
    <Version>1.0.1</Version>
    <Authors>VenEl</Authors>
    <Description>VenEl Core Business Logic - VenEl.MCP.MSSql</Description>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.7" />
    <PackageReference Include="ModelContextProtocol" Version="1.2.0" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VenEl.MCP.Core\VenEl.MCP.Core.csproj" />
  </ItemGroup>

</Project>
