name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build-and-publish-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        os: [win-x64, linux-x64, osx-x64, osx-arm64]
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        
    - name: Pack NuGet Packages
      run: |
        for d in src/VenEl.MCP.*; do
          if [ -d "$d" ]; then
            projName=$(basename "$d")
            # Skip Host or Server projects, just pack the logic libraries
            if [[ "$projName" != *"Host" && "$projName" != *"Server" ]]; then
              dotnet pack "$d/$projName.csproj" -c Release -o nupkg
            fi
          fi
        done
      
    - name: Push to NuGet
      run: dotnet nuget push "nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
